// Decompiled with JetBrains decompiler
// Type: NetworkNews
// Assembly: Assembly-CSharp, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null
// MVID: 4857610B-EF43-43B0-884E-D10225C3A26E
// Assembly location: C:\Users\supdams\Desktop\Assembly-CSharp.dll.dll

#nullable disable
public enum NetworkNews : byte
{
  Login,
  Fallout,
  Refresh,
  Refresh_Asset,
  Refresh_Attr,
  Refresh_Hero,
  Refresh_Item,
  Refresh_Resource,
  Refresh_Stage,
  Refresh_Alliance,
  Refresh_Inputbox,
  Refresh_Mailbox,
  Refresh_Mailing,
  Refresh_Letter,
  Refresh_Battle,
  Refresh_BattleFail,
  Refresh_Building,
  Refresh_ServerTime,
  Refresh_Build,
  Refresh_Barrack,
  Refresh_Soldier,
  Refresh_Hospital,
  Refresh_BuildBase,
  Refresh_QBarTime,
  Refresh_Technology,
  Refresh_Trap,
  Refresh_AttribEffectVal,
  Refresh_HeroExclamation,
  Refresh_ChangeLord,
  Refresh_TroopHome,
  Refresh_BuffList,
  Refresh_SearchList,
  Refresh_Morale,
  Refresh_VIP,
  Refresh_MonsterPoint,
  Refresh_FontTextureRebuilt,
  Refresh_IndemnifyResources,
  Refresh_AllianceWarState,
  Refresh_AllianceWarRound,
  Refresh_RecvAllianceInfo,
  Refresh_PetResource,
  Refresh_SocialNetwork,
  GuestConnectFail,
  GuestLogin,
  GuestLost,
  Refresh_Pet,
  Count,
}
