// Decompiled with JetBrains decompiler
// Type: HERO_EFFECTTYPE_ENUM
// Assembly: Assembly-CSharp, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null
// MVID: 4857610B-EF43-43B0-884E-D10225C3A26E
// Assembly location: C:\Users\supdams\Desktop\Assembly-CSharp.dll.dll

#nullable disable
public enum HERO_EFFECTTYPE_ENUM
{
  HERO_EFFECT_DAMAGE,
  HERO_EFFECT_RECOVER,
  HERO_EFFECT_ADDENERGY,
  HERO_EFFECT_SUBENERGY,
  HERO_EFFECT_DODGE,
  HERO_EFFECT_IMM,
  HERO_EFFECT_PHYSIMM,
  HERO_EFFECT_MAGIIMM,
  HERO_EFFECT_CIR,
  HERO_EFFECT_RECOVER_CIR,
  HERO_EFFECT_DOT,
  HERO_EFFECT_DOT_CIR,
  HERO_EFFECT_HOT,
  HERO_EFFECT_HOT_CIR,
  HERO_EFFECT_HEMOPHAGIA,
  HERO_EFFECT_IMM_BUFF,
  HERO_EFFECT_PHYSIMM_BUFF,
  HERO_EFFECT_MAGIIMM_BUFF,
  HERO_EFFECT_NONE,
}
