// Decompiled with JetBrains decompiler
// Type: EFFECT_ENUM
// Assembly: Assembly-CSharp, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null
// MVID: 4857610B-EF43-43B0-884E-D10225C3A26E
// Assembly location: C:\Users\supdams\Desktop\Assembly-CSharp.dll.dll

#nullable disable
internal enum EFFECT_ENUM
{
  ATTR_STR,
  ATTR_DEX,
  ATTR_INT,
  ATTR_PHYSATK,
  ATTR_MAGIATK,
  ATTR_PHYSDEF,
  ATTR_MAGIDEF,
  ATTR_PHYSCRI,
  ATTR_MAGICRI,
  ATTR_HPRECOVER,
  ATTR_MPRECOVER,
  ATTR_FLEE,
  ATTR_ANTIPHYSDEF,
  ATTR_ANTIMAGIDEF,
  ATTR_MPCOSTDOWN,
  ATTR_VAMPIRE,
  ATTR_AIM,
  ATTR_ADDSKILLLV,
  ATTR_ADDCURE,
  ATTR_ANTISILENCE,
  ATTR_MOVESPD,
  ATTR_ATKRANGE,
  ATTR_ATKSPD,
  ATTR_HPRECOVER_PERSEC,
  ATTR_MPRECOVER_PERSEC,
  ATTR_REDUCEPHYSATK,
  ATTR_REDUCEMAGIATK,
  ATTR_REDUCEATK,
  ATTR_MAX,
  ATTR_ERROR,
}
