// Decompiled with JetBrains decompiler
// Type: EPetSkillExecuteErrorCode
// Assembly: Assembly-CSharp, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null
// MVID: 4857610B-EF43-43B0-884E-D10225C3A26E
// Assembly location: C:\Users\supdams\Desktop\Assembly-CSharp.dll.dll

#nullable disable
public enum EPetSkillExecuteErrorCode
{
  EPSEEC_SUCCEED,
  EPSEEC_SKILL_DATA_NOT_FOUND,
  EPSEEC_IN_CD,
  EPSEEC_UNDEFINE_KIND,
  EPSEEC_NO_PLAYER,
  EPSEEC_BAD_TARGET,
  EPSEEC_PET_NOT_FOUND,
  EPSEEC_PET_DATA_NOT_FOUND,
  EPSEEC_NO_SKILL,
  EPSEEC_NO_SKILL_ITEM,
  EPSEEC_NOT_ACTIVE,
  EPSEEC_SHIELD,
  EPSEEC_UNDEFINE_TARGETTYPE,
  EPSEEC_PET_MARCHING,
  EPSEEC_CONSUMINGVALUE_ZERO,
  EPSEEC_HELPTYPE_ERROR,
  EPSEEC_HELPSTATUS_ERROR,
  EPSEEC_BM_CASTLE_LEVEL_LOW,
  EPSEEC_WALL_MAX,
  EPSEEC_NO_NPCCITYREWARD,
}
