// Decompiled with JetBrains decompiler
// Type: EUILock
// Assembly: Assembly-CSharp, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null
// MVID: 4857610B-EF43-43B0-884E-D10225C3A26E
// Assembly location: C:\Users\supdams\Desktop\Assembly-CSharp.dll.dll

#nullable disable
public enum EUILock
{
  Normal,
  Network,
  Battle,
  HeroList,
  SellItem,
  Hero_Info,
  SoldierTrain,
  Expedition,
  UseItem,
  Synthesis,
  ExitHeroBattle,
  AllianceCreate,
  Alliance_List,
  Alliance_Manage,
  Mailing_Action,
  Mailing_Battle,
  Mailing_Delete,
  Mailing_Read,
  Mailing_Save,
  Hospital,
  LetterEditor,
  BuyItem,
  WatchTower,
  Defender,
  Build,
  Research,
  Alliance_Help,
  BookMark,
  ChangeLord,
  LordInfo,
  SearchPlayer,
  Scout,
  AllyPoint,
  ResPointOwnerLv,
  Mission,
  Inforce,
  LordEquip,
  Activity,
  TreasureBox,
  Rally,
  SwitchAccount,
  BindAccount,
  Mall,
  Crypt,
  Jail,
  MessageBoard,
  Alliance_Gift,
  Arena,
  HideArmy,
  KingdomBullitin,
  Amnesty,
  Title,
  KingGift,
  WorldTeleport,
  AllanceDismissLeader,
  WeChatPay,
  AliPay,
  Ambush,
  BlackMarket,
  SwitchingGoogleAccount,
  SetTroopmemory,
  AllianceMobilization,
  AllianceChangHomeKingdom,
  Alchemy,
  UIBattleGambling,
  UIDonation,
  CastleSkin,
  WonderReward,
  AWS_Schedule,
  AllianceWar_Fs,
  ForceNewbie,
  PetFusion,
  PetUI,
  PetSkill,
  PetSelect,
  ActGift,
  All,
}
