// Decompiled with JetBrains decompiler
// Type: GameMaintanceData
// Assembly: Assembly-CSharp, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null
// MVID: 4857610B-EF43-43B0-884E-D10225C3A26E
// Assembly location: C:\Users\supdams\Desktop\Assembly-CSharp.dll.dll

#nullable disable
public struct GameMaintanceData
{
  public string IsMaintain;
  public string Message_Tw;
  public string Message_Eg;
  public string Message_DE;
  public string Message_FR;
  public string Message_ES;
  public string Message_RU;
  public string Message_CN;
  public string Message_ID;
  public string Message_VI;
  public string Message_TR;
  public string Message_TH;
  public string Message_IT;
  public string Message_PT;
  public string Message_KO;
  public string Message_JP;
  public string Message_UA;
  public string Message_MY;
  public string Message_ARB;
  public string StartTime;
  public string EndTime;
  public string LoginBoxMsg_Tw;
  public string LoginBoxMsg_Eg;
  public string LoginBoxMsg_DE;
  public string LoginBoxMsg_FR;
  public string LoginBoxMsg_ES;
  public string LoginBoxMsg_RU;
  public string LoginBoxMsg_CN;
  public string LoginBoxMsg_ID;
  public string LoginBoxMsg_VI;
  public string LoginBoxMsg_TR;
  public string LoginBoxMsg_TH;
  public string LoginBoxMsg_IT;
  public string LoginBoxMsg_PT;
  public string LoginBoxMsg_KO;
  public string LoginBoxMsg_JP;
  public string LoginBoxMsg_UA;
  public string LoginBoxMsg_MY;
  public string LoginBoxMsg_ARB;
  public string LoginBoxStartTime;
  public string LoginBoxEndTime;
  public string VersionCode;
  public string MinVersion;
  public string URL;
  public string Version;
  public string Package;
  public string Size;
  public string loginInfo_Tw;
  public string loginInfo_Eg;
  public string UpdateInfo_Tw;
  public string UpdateInfo_Eg;
  public string UpdateInfo_DE;
  public string UpdateInfo_FR;
  public string UpdateInfo_ES;
  public string UpdateInfo_RU;
  public string UpdateInfo_CN;
  public string UpdateInfo_ID;
  public string UpdateInfo_VI;
  public string UpdateInfo_TR;
  public string UpdateInfo_TH;
  public string UpdateInfo_IT;
  public string UpdateInfo_PT;
  public string UpdateInfo_KO;
  public string UpdateInfo_JP;
  public string UpdateInfo_UA;
  public string UpdateInfo_MY;
  public string UpdateInfo_ARB;
  public string StarStatus;
  public string TranslateStatus;
  public string RealNameCheck;
  public string MinorsDailySpendAmount;
  public string AddictedCheckNotice;
  public string AddictedCheckLimitLogin;
  public string OtherDownloadUrl;
  public LoginServerData[] LoginServer;
}
