// Decompiled with JetBrains decompiler
// Type: HERO_STATE_ENUM
// Assembly: Assembly-CSharp, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null
// MVID: 4857610B-EF43-43B0-884E-D10225C3A26E
// Assembly location: C:\Users\supdams\Desktop\Assembly-CSharp.dll.dll

#nullable disable
public enum HERO_STATE_ENUM : byte
{
  HERO_COMMANDS_IDLE = 0,
  HERO_COMMANDS_MOVE = 1,
  HERO_COMMANDS_ATTACK = 2,
  HERO_COMMANDS_RANGE_PARTICLE = 3,
  HERO_COMMANDS_GETHIT = 4,
  HERO_COMMANDS_DIE = 5,
  HERO_COMMANDS_CHANGE_SIEGE_MODE = 6,
  HERO_COMMANDS_RANGE = 6,
  HERO_COMMANDS_RANGE_POINT = 7,
  HERO_COMMANDS_GOT_STATE = 8,
  HERO_COMMANDS_REMOVE_STATE = 9,
  HERO_COMMANDS_HPMP_MODIFY = 10, // 0x0A
  HERO_COMMANDS_CHANNEL_SKILL = 11, // 0x0B
  HERO_COMMANDS_STOP_CHANNEL = 12, // 0x0C
  HERO_COMMANDS_HITPOINT = 13, // 0x0D
  HERO_COMMANDS_GROUND_SKILL = 14, // 0x0E
  HERO_COMMANDS_CHARGE_POINT = 15, // 0x0F
  HERO_COMMANDS_CHARGE_POINT_END = 16, // 0x10
  HERO_COMMANDS_CHARGE_TARGET = 17, // 0x11
  HERO_COMMANDS_CHARGE_TARGET_END = 18, // 0x12
  HERO_COMMANDS_KNOCK_BACK = 19, // 0x13
  HERO_COMMANDS_KNOCK_BACK_END = 20, // 0x14
  HERO_COMMANDS_SUPPORT = 21, // 0x15
  HERO_COMMANDS_CASINOHIT = 22, // 0x16
  HERO_COMMANDS_VICTORY = 23, // 0x17
  HERO_COMMANDS_VICTORY_LOOP = 24, // 0x18
  HERO_COMMANDS_VICTORY_IDLE = 25, // 0x19
  HERO_COMMANDS_VICTORY_RUN = 26, // 0x1A
  HERO_COMMANDS_VICTORY_RUN_GAMBLE = 27, // 0x1B
  HERO_COMMANDS_PVPNPC_IDLE = 28, // 0x1C
  HERO_COMMANDS_CHARGE_DAZE = 29, // 0x1D
  HERO_COMMANDS_WAITING_SUPPORT = 30, // 0x1E
  HERO_COMMANDS_SUPPORT_DISPLAY = 31, // 0x1F
  HERO_COMMANDS_FINISHING_SPREAD = 32, // 0x20
  HERO_COMMANDS_GAMBLEFAILED = 33, // 0x21
}
