// Decompiled with JetBrains decompiler
// Type: WindowPrefabData
// Assembly: Assembly-CSharp, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null
// MVID: 4857610B-EF43-43B0-884E-D10225C3A26E
// Assembly location: C:\Users\supdams\Desktop\Assembly-CSharp.dll.dll

using System;

#nullable disable
public struct WindowPrefabData
{
  public string m_PrefabName;
  public Type m_WindowType;
  public string m_OptName;
  public static readonly WindowPrefabData[] Data = new WindowPrefabData[187]
  {
    new WindowPrefabData("UIOrigin", typeof (Door)),
    new WindowPrefabData("UIBattle", typeof (UIBattle)),
    new WindowPrefabData("UIStageInfo", typeof (UIStageInfo)),
    new WindowPrefabData("UIStageStory", typeof (UIStageStory)),
    new WindowPrefabData("UIStageSelect", typeof (UIStageSelect), "UIStageSelect"),
    new WindowPrefabData("UIStageSelect", typeof (UIStageSelect2), "UIStageSelect2"),
    new WindowPrefabData("UISettlement", typeof (UISettlement)),
    new WindowPrefabData("UIHeroList", typeof (UIHeroList), "UIHeroList"),
    new WindowPrefabData("UIBattleHeroSelect", typeof (UIBattleHeroSelect)),
    new WindowPrefabData("UIHero_Info", typeof (UIHero_Info), "UIHero_Info"),
    new WindowPrefabData("UIBattleReport", typeof (UIBattleReport), "UIBattleReport"),
    new WindowPrefabData("UIResourceBuilding", typeof (UIResourceBuilding)),
    new WindowPrefabData("UISuitBuilding", typeof (UISuitBuilding)),
    new WindowPrefabData("UIBagAndFilter", typeof (UIBagFilter), "UIBagShop"),
    new WindowPrefabData("UIChat", typeof (UIChat)),
    new WindowPrefabData("UIHeroList_Soldier", typeof (UIHeroList_Soldier)),
    new WindowPrefabData("UIBarrack", typeof (UIBarrack)),
    new WindowPrefabData("UIBarrack_Soldier", typeof (UIBarrack_Soldier)),
    new WindowPrefabData("UIHospital", typeof (UIHospital)),
    new WindowPrefabData("UIExpedition", typeof (UIExpedition), "UIExpedition"),
    new WindowPrefabData("UIBagAndFilter", typeof (UIBookMark), "UIBookMark"),
    new WindowPrefabData("UIAllianceHint", typeof (AllianceHint)),
    new WindowPrefabData("UIAllianceInput", typeof (InputBox)),
    new WindowPrefabData("UIAlliance_Info", typeof (UILanguageSelect), "UILanguageSelect"),
    new WindowPrefabData("UISynthesis", typeof (UISynthesis)),
    new WindowPrefabData("UIAlliance_Info", typeof (UIAlliance_List), "UIAlliance_List"),
    new WindowPrefabData("UIAlliance_Info", typeof (UIAlliance_Permission), "UIAlliance_Permission"),
    new WindowPrefabData("UIAlliance_Info", typeof (UIAlliance_Info), "UIAlliance_Info"),
    new WindowPrefabData("UIAlliance_Info", typeof (UIAlliance_publicinfo), "UIAlliance_publicinfo"),
    new WindowPrefabData("UIAlliance_Info", typeof (UIAlliance_Badge), "UIAlliance_Badge"),
    new WindowPrefabData("UIWarehouse", typeof (UIWarehouse)),
    new WindowPrefabData("UIWatchtower", typeof (UIWatchtower)),
    new WindowPrefabData("UIWatchtower_Details", typeof (UIWatchtower_Details)),
    new WindowPrefabData("UIDevelopmentDetails", typeof (UIDevelopmentDetails)),
    new WindowPrefabData("UILegBattle", typeof (UILegBattle)),
    new WindowPrefabData("UI_leadup", typeof (UI_leadup)),
    new WindowPrefabData("UIBattleReport", typeof (UI_NewTerritory), "UI_NewTerritory"),
    new WindowPrefabData("UIAlliance_Management", typeof (UIAlliance_Management)),
    new WindowPrefabData("UIHeroUse", typeof (UIHeroUse)),
    new WindowPrefabData("UIArmyInfo", typeof (UIArmyInfo)),
    new WindowPrefabData("UI_Information", typeof (UIInformation)),
    new WindowPrefabData("UITechTree", typeof (UITechTree), "UITechTree"),
    new WindowPrefabData("UITechTree", typeof (UITechInstitute), "UITechInstitute"),
    new WindowPrefabData("UITechTree", typeof (UITechUpgrade), "UITechUpgrade"),
    new WindowPrefabData("UILetter", typeof (UILetter), "UILetter"),
    new WindowPrefabData("UICityWall", typeof (UICityWall)),
    new WindowPrefabData("UIMarket", typeof (UIMarket)),
    new WindowPrefabData("UIMarket_Help", typeof (UIMarket_Help)),
    new WindowPrefabData("UIEmbassy", typeof (UIEmbassy)),
    new WindowPrefabData("UIFightingSummary", typeof (UIFightingSummary), "UIFightingSummary"),
    new WindowPrefabData("UIFightingSummary_Info", typeof (UIFightingSummary_Info)),
    new WindowPrefabData("UILetter_Watchtower", typeof (UILetter_Watchtower), "UILetter_Watchtower"),
    new WindowPrefabData("UILetterEditor", typeof (UILetterEditor)),
    new WindowPrefabData("UIDefenders", typeof (UIDefenders)),
    new WindowPrefabData("UILetterDetail", typeof (UILetterDetail)),
    new WindowPrefabData("UIWarLobby", typeof (UIWarLobby)),
    new WindowPrefabData("UIWallRepair", typeof (UIWallRepair)),
    new WindowPrefabData("UIAlliance_Info", typeof (UIAlliance_Rally), "UIAlliance_Rally"),
    new WindowPrefabData("UITrap", typeof (UITrap)),
    new WindowPrefabData("UIExpedition", typeof (UIHeroList_Soldier2), "UIHeroList_Soldier2"),
    new WindowPrefabData("UICastle", typeof (UICastle)),
    new WindowPrefabData("UICastleUpgradeReward", typeof (UICastleUpgradeReward)),
    new WindowPrefabData("UILetter_Resources", typeof (UILetter_Resources), "UILetter_Resources"),
    new WindowPrefabData("UILetter_Resources", typeof (UILetter_Collection), "UILetter_Collection"),
    new WindowPrefabData("UIAlliance_Info", typeof (UIAlliance_HelpSpeedup), "UIAlliance_HelpSpeedup"),
    new WindowPrefabData("UIReplaceLord", typeof (UIReplaceLord)),
    new WindowPrefabData("UI_LordInfo", typeof (UILordInfo), "UI_LordInfo"),
    new WindowPrefabData("UIBuffList", typeof (UIBuffList), "UIBuffList"),
    new WindowPrefabData("UIForge", typeof (UIForge)),
    new WindowPrefabData("UITalent", typeof (UITalent), "UITalentTree"),
    new WindowPrefabData("UIActivity", typeof (UIActivity1), "UIActivity1"),
    new WindowPrefabData("UIActivity2", typeof (UIActivity2), "UIActivity2"),
    new WindowPrefabData("UIActivity3", typeof (UIActivity3), "UIActivity3"),
    new WindowPrefabData("UIActivity", typeof (UIActivity4), "UIActivity4"),
    new WindowPrefabData("UIMall", typeof (UIMall), "UIMall"),
    new WindowPrefabData("UIMall", typeof (UIMall_Detail), "UIMall_Detail"),
    new WindowPrefabData("UI_OpenBox", typeof (UIOpenBox)),
    new WindowPrefabData("UISearchList", typeof (UISearchList)),
    new WindowPrefabData("UIOther", typeof (UIOther), "UIOther"),
    new WindowPrefabData("UI_VIP", typeof (UIVIP)),
    new WindowPrefabData("UIMission", typeof (UIMission)),
    new WindowPrefabData("UI_HeroTalk", typeof (UIHeroTalk)),
    new WindowPrefabData("UIOther", typeof (UIOther_FunctionSwitch), "UIOther_FunctionSwitch"),
    new WindowPrefabData("UIOther", typeof (UIOther_Forum), "UIOther_Forum"),
    new WindowPrefabData("UIOther", typeof (UIOther_Set), "UIOther_Set"),
    new WindowPrefabData("UIAltar", typeof (UIAltar)),
    new WindowPrefabData("UI_Jail", typeof (UIJail)),
    new WindowPrefabData("UI_JailMoney", typeof (UIJailMoney)),
    new WindowPrefabData("UI_JailRoom", typeof (UIJailRoom)),
    new WindowPrefabData("UIChapterRewards", typeof (UIChapterRewards)),
    new WindowPrefabData("UI_LordEquip", typeof (UILordEquip)),
    new WindowPrefabData("UI_EffectFilter", typeof (UIEffectFilter)),
    new WindowPrefabData("UIForge_Item", typeof (UIForge_Item), "UIForge_Item"),
    new WindowPrefabData("UIForge_Item", typeof (UIForge_ActivityItem), "UIForge_ActivityItem"),
    new WindowPrefabData("UIOther_Account", typeof (UIOther_Account)),
    new WindowPrefabData("UITBWindow", typeof (UITreasureBox), "UITreasureBox"),
    new WindowPrefabData("UI_ForgeAnvil", typeof (UIAnvil)),
    new WindowPrefabData("UI_PriestTalk", typeof (UIPriestTalk)),
    new WindowPrefabData("UI_Crypt", typeof (UICrypt), "UI_CryptBuild"),
    new WindowPrefabData("UI_Crypt", typeof (UICryptDig), "UI_CryptDig"),
    new WindowPrefabData("UI_VIPLevelUP", typeof (UIVIPLevelUP)),
    new WindowPrefabData("UI_LeaderBoard", typeof (UILeaderBoard)),
    new WindowPrefabData("UIBlackList", typeof (UIBlackList)),
    new WindowPrefabData("UIMapMonster", typeof (UIMapMonster), "UIWorldMonster"),
    new WindowPrefabData("UIMapMonster", typeof (UIMonsterInfo), "UIMonsterInfo"),
    new WindowPrefabData("UIAlliance_Gift", typeof (UIAlliance_Gift)),
    new WindowPrefabData("UIMessageBoard", typeof (UIMessageBoard)),
    new WindowPrefabData("UIHeroUp", typeof (UIHeroUp)),
    new WindowPrefabData("UIAnnouncement", typeof (UIAnnouncement)),
    new WindowPrefabData("UIArena", typeof (UIArena), "UIArena"),
    new WindowPrefabData("UIArena", typeof (UIArena_Replay), "UIArena_Replay"),
    new WindowPrefabData("UIArena", typeof (UIArena_Info), "UIArena_Info"),
    new WindowPrefabData("UIArena", typeof (UIArena_I), "UIArena_I"),
    new WindowPrefabData("UIWonderLand", typeof (UIWonderLand), "UIWonderLand"),
    new WindowPrefabData("UIWonderLand", typeof (UIWonderInfo), "UIWonderInfo"),
    new WindowPrefabData("UIMiniMap", typeof (UIMiniMap), "UIMiniMap"),
    new WindowPrefabData("UIFront", typeof (UIFront)),
    new WindowPrefabData("UIName", typeof (UIName)),
    new WindowPrefabData("UI_LordEquipSetEdit", typeof (UILordEquipSetEdit)),
    new WindowPrefabData("UITalentSave", typeof (UITalentSave)),
    new WindowPrefabData("UITalentSave", typeof (UISetSelect)),
    new WindowPrefabData("UIKingdom_Classifieds", typeof (UIKingdom_Classifieds)),
    new WindowPrefabData("UITitle", typeof (UITitle)),
    new WindowPrefabData("UIPaySetting", typeof (UIPaySetting)),
    new WindowPrefabData("UIAmbush", typeof (UIAmbush)),
    new WindowPrefabData("UIMerchantman", typeof (UIMerchantman)),
    new WindowPrefabData("UITalentSave", typeof (UITeamSave)),
    new WindowPrefabData("UIBuffInformation", typeof (UIBuffInformation)),
    new WindowPrefabData("UI_FormationSelect", typeof (UIFormationSelect)),
    new WindowPrefabData("UIMall", typeof (UIRewardsSelect), "UIRewardsSelect"),
    new WindowPrefabData("UIAlliance_Mobilization", typeof (UIAlliance_Mobilization), "UIAlliance_Mobilization"),
    new WindowPrefabData("UIAlliance_Mobilization", typeof (UIAlliance_Mobilization_Info), "UIAlliance_Mobilization_Info"),
    new WindowPrefabData("UIWonderLand", typeof (UIWonderReward), "UIWonderReward"),
    new WindowPrefabData("UICanonizedPanel", typeof (UICanonizedPanel)),
    new WindowPrefabData("UI_Immigration", typeof (UIImmigration)),
    new WindowPrefabData("UI_LeaderBoard", typeof (UIKingdomVSLBoard)),
    new WindowPrefabData("UI_LeaderBoard", typeof (UIKVKLBoard)),
    new WindowPrefabData("UIBattle_Gambling", typeof (UIBattle_Gambling)),
    new WindowPrefabData("UIAlchemy", typeof (UIAlchemy)),
    new WindowPrefabData("UILetter_Watchtower", typeof (UILetter_NPCScout), "UILetter_Watchtower"),
    new WindowPrefabData("UIMonster_Crypt_3", typeof (UIMonster_Crypt_3)),
    new WindowPrefabData("UIMonster_Crypt", typeof (UIMonsterCrypt)),
    new WindowPrefabData("UITBWindow", typeof (UIChallegeTreasure), "UIChallegeReward"),
    new WindowPrefabData("UI_LeaderBoard", typeof (UIAlliHuntBoard)),
    new WindowPrefabData("UIEmojiSelect", typeof (UIEmojiSelect)),
    new WindowPrefabData("UIDonation", typeof (UIDonation), "UIDonation"),
    new WindowPrefabData("UIDonation", typeof (UIDonation_Info), "UIDonation_Info"),
    new WindowPrefabData("UIMapMonster", typeof (UISummonMonster), "UISummonMonster"),
    new WindowPrefabData("UISuicideBox", typeof (UISuicideBox)),
    new WindowPrefabData("UICastleSkin", typeof (UICastleSkin), "UICastleSkinView"),
    new WindowPrefabData("UICastleSkin", typeof (UICastleStrengthen), "UICastleStrengthen"),
    new WindowPrefabData("UI_LeaderBoard", typeof (UINobilityBoard)),
    new WindowPrefabData("UI_LeaderBoard", typeof (UINobilityOccupyBoard)),
    new WindowPrefabData("UI_LordInfo", typeof (UIESportProfile)),
    new WindowPrefabData("UILetter_Watchtower", typeof (UILetter_Watchtower_Recon), "UILetter_Watchtower_Recon"),
    new WindowPrefabData("UIFightingSummary", typeof (UIAlliance_FS), "UIFightingSummary"),
    new WindowPrefabData("UIFightingSummary_Info", typeof (UIAlliance_FS_Info)),
    new WindowPrefabData("UIAllianceWarOver", typeof (UIAllianceWarOver)),
    new WindowPrefabData("UI_LeaderBoard", typeof (UIAlliVSGroupBoard)),
    new WindowPrefabData("UI_LeaderBoard", typeof (UIAlliVSAlliBoard)),
    new WindowPrefabData("UIAllianceMatchInfo", typeof (UIAllianceMatchInfo)),
    new WindowPrefabData("UI_AllianceWar_Register", typeof (UIAllianceWarRegister)),
    new WindowPrefabData("UIAllianceWar_Rank", typeof (UIAllianceWar_Rank)),
    new WindowPrefabData("UIAllianceBattle", typeof (UIAllianceWarBattle)),
    new WindowPrefabData("UI_AlliWarSchedule", typeof (UI_AlliWarSchedule)),
    new WindowPrefabData("UIMall", typeof (UIMall_FG), "UIMall_FG"),
    new WindowPrefabData("UIMall", typeof (UIMall_FG_Detail), "UIMall_FG_Detail"),
    new WindowPrefabData("UIPetFusionbuilding", typeof (UIPetFusionbuilding)),
    new WindowPrefabData("UIPetFusion", typeof (UIPetFusion)),
    new WindowPrefabData("UI_PetResourceStation", typeof (UI_PetResourceStation)),
    new WindowPrefabData("UIFightingSummary", typeof (UIPetSkill_FS), "UIPetSkill_FS"),
    new WindowPrefabData("UIItemCraftShow", typeof (UIItemCraftShow)),
    new WindowPrefabData("UIHeroList", typeof (UIPetBag), "UIPetBag"),
    new WindowPrefabData("UIPetList", typeof (UIPetList)),
    new WindowPrefabData("UIPet", typeof (UIPet), "UIPet"),
    new WindowPrefabData("UIPet", typeof (UIPetStoneTrans), "UIPetStoneTrans"),
    new WindowPrefabData("UIPetBuff", typeof (UIPetBuff)),
    new WindowPrefabData("UIPetBuff", typeof (UIPetSkill), "UIPetSkill"),
    new WindowPrefabData("UIPetBuff", typeof (UIPetBuff), "UIPetBuff"),
    new WindowPrefabData("UIExpedition", typeof (UIPetSelect), "UIPetSelect"),
    new WindowPrefabData("UIPetTrainingCenter", typeof (UIPetTrainingCenter)),
    new WindowPrefabData("UITBWindow", typeof (UIPetLevelUp), "UIPetLevelUp"),
    new WindowPrefabData("UIAlliance_Info", typeof (UIAlliance_ActivityGift), "UIAlliance_ActivityGift"),
    new WindowPrefabData("UITBWindow", typeof (UITreasureBox_FB), "UITreasureBox_FB"),
    new WindowPrefabData("UIFBMission", typeof (UIFBWindow), "UIFBWindow"),
    new WindowPrefabData("UIMall", typeof (UIBackReward), "UIBackReward"),
    new WindowPrefabData("UIMall", typeof (UIBackReward_Detail), "UIBackReward_Detail")
  };

  public WindowPrefabData(string n, Type t, string o = null)
  {
    this.m_PrefabName = n;
    this.m_WindowType = t;
    this.m_OptName = o;
  }
}
