// Decompiled with JetBrains decompiler
// Type: Btn_Count
// Assembly: Assembly-CSharp, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null
// MVID: 4857610B-EF43-43B0-884E-D10225C3A26E
// Assembly location: C:\Users\supdams\Desktop\Assembly-CSharp.dll.dll

#nullable disable
public enum Btn_Count
{
  btn_Count,
  btn_EXIT,
  btn_Page1,
  btn_Page2,
  btn_Page3,
  btn_Evolution,
  btn_Equip1,
  btn_Equip2,
  btn_Equip3,
  btn_Equip4,
  btn_Equip5,
  btn_Equip6,
  btn_EquipStratum,
  btn_StarEvolution,
  btn_DETAIL,
  btn_Skill1,
  btn_Skill2,
  btn_Skill3,
  btn_Skill4,
  NextBtn,
  BackBtn,
  btn_HeroAction,
  btn_RankEquip1,
  btn_RankEquip2,
  btn_RankEquip3,
  btn_RankEquip4,
  btn_RankEquip5,
  btn_RankEquip6,
  btn_Rank_Exit,
  btn_Evolve_OK,
  btn_Evolve_Cancel,
  btn_P3Info,
  btn_SkillPage1,
  btn_SkillPage2,
  btn_Skill5,
  btn_Skill6,
  btn_Skill7,
  btn_Skill8,
  btn_Property,
  btn_Fragment,
  btn_Property_S,
  btn_Property_D,
  btn_Property_I,
  btn_ItemHint,
  btn_HeroState,
  btn_HeroPowerHint,
}
