// Decompiled with JetBrains decompiler
// Type: EFBEvent
// Assembly: Assembly-CSharp, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null
// MVID: 4857610B-EF43-43B0-884E-D10225C3A26E
// Assembly location: C:\Users\supdams\Desktop\Assembly-CSharp.dll.dll

#nullable disable
public enum EFBEvent
{
  SUPPLY_CHEST,
  CASTLE_LEVEL,
  FIRST_CONQUER_TURF_BATTLE,
  FIRST_UNLOCK_NORMAL_CHAPTER,
  CREDITS_FOR_KVK,
  CREDITS_FOR_GUILD_FEST,
  COLLECT_EXTRA_SUPPLIES,
  FIRST_PACT_OPENED,
  FIRST_LINEUP_DRILL,
  FIRST_EXECUTION,
  FIRST_TRANSMUTATION,
  FIRST_EQUIPMENT_FORGED,
  FIRST_CARGO_SHIP_EXCHANGE,
  FIRST_GUILD_SHOWDOWN_REGISTRATION,
  FIRST_GUILD_FEST_QUEST,
  MAX,
}
