// Decompiled with JetBrains decompiler
// Type: EWATCHTOWER_LINE_TARGET
// Assembly: Assembly-CSharp, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null
// MVID: 4857610B-EF43-43B0-884E-D10225C3A26E
// Assembly location: C:\Users\supdams\Desktop\Assembly-CSharp.dll.dll

#nullable disable
public enum EWATCHTOWER_LINE_TARGET : byte
{
  EWATCHTOWER_LINE_TARGET_CAPITAL,
  EWATCHTOWER_LINE_TARGET_CAMP,
  EWATCHTOWER_LINE_TARGET_AMBUSH,
  EWATCHTOWER_ADDLINE_WONDER1,
  EWATCHTOWER_ADDLINE_WONDER2,
  EWATCHTOWER_ADDLINE_WONDER3,
  EWATCHTOWER_ADDLINE_WONDER4,
  EWATCHTOWER_ADDLINE_WONDER5,
  EWATCHTOWER_ADDLINE_WONDER6,
  EWATCHTOWER_ADDLINE_WONDER7,
}
